### ISSUE TITLE
[Repository] Load sub-item on click : option to no reload immediately

### ISSUE THREAD

**Issue by troussej** [jc7447/BetterDynAdmin#106]
Sometimes I want to display several sub-items on a result, and I don't want to reload the page each time.

The alert popup could propose 3 options : reload, just add, cancel.

**Comment by troussej** [comment]
duh there is no native JS to do that :(

**Comment by troussej** [comment]
Done.

**Comment by jc7447** [comment]
Merged on master for version 2.1
