### ISSUE TITLE
[JDBC] JDBC page crashes on Chrome

### ISSUE THREAD

**Issue by troussej** [jc7447/BetterDynAdmin#107]
The JDBC page crashes on Chrome. Looks like it's liked to a synchronous ajax call ( which should be avoided anyway) that loops indefinetely on /dyn/admin/nucleusundefined

VM145:8 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.send 
@ VM145:8ajax 
@ VM145:8getCurrentDataSource 
@ VM145:4240setupExecuteQueryPage 
@ VM145:4175build 
@ VM145:4156$.fn.bdajdbc 
@ VM145:4276init 
@ VM145:10733(anonymous function) 
@ VM145:10883(anonymous function) 
@ VM145:10894j 
@ VM145:6k 
@ VM145:6(anonymous function) 
@ VM106:2e.string.c.(anonymous function) 
@ VM144:54

**Comment by troussej** [comment]
Fix pushed to dev.

**Comment by troussej** [comment]
fixed the loop (weird i != array.length)

The async ajax calls should still be fixed

**Comment by jc7447** [comment]
It's fixed now
