### ISSUE TITLE
[Toolbar] Add the ability to update variables, methods and tags to a toolbar item after it's been created

### ISSUE THREAD

**Issue by talanb** [jc7447/BetterDynAdmin#115]
Once a favorite has been added to the toolbar, I would like to be able to add additional variables, methods, and tags without re-creating the toolbar item.

**Comment by sixdouglas** [comment]
Hi,
There is no possibility to update favorites yet.
However a possibility is to export the Favorites in JSon, edit it and then reimport the whole. This is clearly a workaround. Let us know if you face any problem.

**Comment by troussej** [comment]
Just pushed to dev branch the ability to edit a fav.
