### ISSUE TITLE
[DASH] Ability to set values as "null".

### ISSUE THREAD

**Issue by troussej** [jc7447/BetterDynAdmin#116]
Hey all,

A colleague of mine asked me if it was possible to set values as null with a dash script.

i'm not currently working on ATG so I can't test this. If it's possible using a string in standard dyn/admin, it should be the same using dash.

Can someone test this?

(anyway I might soon rework on ATG, for a bike company...)

**Comment by talanb** [comment]
I just tested this and it worked.

`set /com/meredith/commerce/autorenew/AutoRenewConfig.configLayer null`

**Comment by troussej** [comment]
Thx !
