### ISSUE TITLE
grant window.focus

### ISSUE THREAD

**Issue by fape** [jc7447/BetterDynAdmin#31]
Please add some new @grant. Usefull for chrome user. Thanks
- http://tampermonkey.net/documentation.php#_grant
- https://github.com/derjanb/tampermonkey/issues/253

eg. window.focus() is used by codemirror

**Comment by jc7447** [comment]
Ok, I will check this

Thanks you to reporting

**Comment by fape** [comment]
Thanks. That was quick.
