### ISSUE TITLE
[Chrome] ItemTree use a deprecated method

### ISSUE THREAD

**Issue by onewingedfallen59** [jc7447/BetterDynAdmin#38]
When you do a get item tree, whatever repository or descriptor, the following will be logged on Google Chrome 47 console :

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
VM5277:2647 descriptor : 55

**Comment by jc7447** [comment]
This happen when getting the repository configuration for the item tree.
It can be avoid but has no consequence on UX or performance.
