### ISSUE TITLE
[Repository] Improve "Cache usage statistics" table

### ISSUE THREAD

**Issue by jc7447** [jc7447/BetterDynAdmin#42]
- Use even/odd to distinct each line
- Make the header sticky with the scrollbar

**Comment by troussej** [comment]
I started working on this, but I have some readability and perf issues.

I'm making each line collapsible, and I want to start everything collapsed. but on big repos, this takes up to 500ms during the init phase.

Maybe you could have a look at it? (https://github.com/troussej/BetterDynAdmin/tree/repository/cache_stats )

**Comment by jc7447** [comment]
I just take a look, in _toggleCacheLines_ you are using JQuery _slideToggle_ which perform an animation to hide the element.

Since you are using this function to handle click on the arrow and also to toggle off all lines at initialization time, you are performing X slide animations (X = number of item descriptor)

Default duration for the animation is 400ms, I'm surprised it doesn't take more time to render ! May be there is some JQuery or browser optimization to run several animation at the same time.

Anyway, I replaced _.slideToggle()_ with _[.toggle()](http://api.jquery.com/toggle/)_, for a repository with 60 item descriptors, it took 705 ms with _slideToggle()_ and 140 ms with _toggle()_. I tried _slideToggle(0)_, but it's the same as _slideToggle()_.

May be you can add a boolean parameter to  _toggleCacheLines_  to know if you want to trigger the slide animation or not and use _toggle_ and _slideToggle_ accordingly.

**Comment by troussej** [comment]
- changed the css so that it's more legible
- collapse/expand per line

looks like setting up a sticky header is pretty tricky, I've seen plugins over 300 lines to do that ...

**Comment by troussej** [comment]
i think this can be closed for now.
