### ISSUE TITLE
[Pipeline] Show pipeline details for each chain

### ISSUE THREAD

**Issue by jc7447** [jc7447/BetterDynAdmin#44]
In the main page of a pipeline manager, make chain name clickable. 
On click, show pipeline details as XML with a graphical representation of the chain (http://stackoverflow.com/questions/7034/graph-visualization-library-in-javascript, http://www.graphdracula.net/)

- [x] show pipeline
- [x] show transition value

**Comment by jc7447** [comment]
- Propose a switch button to represent graph from left to right or top to bottom

http://visjs.org/examples/network/layout/hierarchicalLayout.html

**Comment by jc7447** [comment]
- Make node clickable : open a new browser tab to the component page
- Add return value in the edges

**Comment by troussej** [comment]
Try to get a neat ordering : for now there is a bit of back and forth, see ss.

![chain_order](https://cloud.githubusercontent.com/assets/8314012/13117796/adb79b28-d5a1-11e5-86fe-92f25bb21732.png)

**Comment by troussej** [comment]
also : the "show xml" button should also toggle off the xml snippet.

**Comment by jc7447** [comment]
Node are now clickable, there is a toggle off button for xml and a switch button to change graph orientation.

This feature is still in beta for now, pipeline chain with lot of processors and without any fork are still not well readable. 

I close this issue, we can continue to improve it though other task.
