### ISSUE TITLE
[Repository] create a button which only run highlighted/selected query

### ISSUE THREAD

**Issue by onewingedfallen59** [jc7447/BetterDynAdmin#57]

**Comment by troussej** [comment]
This might be a requirement to do #72

**Comment by troussej** [comment]
after looking at how it's done, the issue is that for now we use the xml textarea in the native way, by posting the whole page. We would need to do ajax calls (better but complicated), or post the page by changing the text, then restoring the whole thing... which already seems ugly

**Comment by jc7447** [comment]
Yeah, it sounds like a lot of trouble for a tiny benefit.  I'm also afraid that most of the people won't get the feature.

Let's put this aside for the moment, will see if we get better idea later :)

**Comment by troussej** [comment]
Now that we have the ajax call to do rql we could think of ajaxifying the repo page or enhancing Dash to have a display similar to the repo page. It's still a big overhaul of the page, not sure it's worth the trouble.

**Comment by troussej** [comment]
to be included in #123
