### ISSUE TITLE
[Bookmarks] Create folders for bookmarks

### ISSUE THREAD

**Issue by troussej** [jc7447/BetterDynAdmin#58]
Ability to create folders for the bookmarks

**Comment by troussej** [comment]
Working on a version of that: add tags to faves, and filter by tag. Almost ready :)

Screenshot attached, and live version in the master of my fork.

 I'm not very happy with the chevron (vertical ">") that opens the filter bar. I want the "tag bar" to be collapsable to save vertical space, but can't seem to find a good place for the button that opens it.

Right now it takes too much place for my taste.

Feedback is welcome.

 When filters are opened:
![bda-filters-closed](https://cloud.githubusercontent.com/assets/8314012/14575192/8935c6b6-0360-11e6-8f81-0caa962b9e52.png)

Tag reminder added to the fav:
![bda-filters](https://cloud.githubusercontent.com/assets/8314012/14575074/d3274b56-035f-11e6-805b-9898875608b9.png)

**Comment by jc7447** [comment]
Looks pretty nice :)

I'm time short those days, I will check this probably next week.

**Comment by troussej** [comment]
I've worked some more lately i'll show you ;)
Le 22 avr. 2016 20:29, "Jean-Charles Manoury" <notifications@github.com> a
écrit :

**Comment by troussej** [comment]
so.. i'm finished with this dev, but being a Git n00b I think I messed up the way my branches are done,  i.e. the starting point of my branch is ahead of the fork point with your repo... so that if try to do a pull request, it will also take into account others commits :

I've tried to do some rebases, but entered conflict hell... so.. I might need the help of a git guru :P

**Comment by jc7447** [comment]
Seems that you have overcame this branch hell :) 

I have merged your pull #77, the result is very cool, thanks you :)

I will open a new task to add the ability to edit an existing favorite component (just reopen the pop-up should be enough), so people who have already a lot of favorites can benefit from the new tag system and default properties/methods also.
