### ISSUE TITLE
[Refactor] Split the main script in modules

### ISSUE THREAD

**Issue by troussej** [jc7447/BetterDynAdmin#65]
The BDA script is getting really big and difficult to read. It would benefit from being split into several modules (repositories, pipelines, bookmarks) 

It should be easy using "require" statements

**Comment by troussej** [comment]
I'm going to draft a proposal for modularisation

**Comment by jc7447** [comment]
Joël, if you're time-short for this, let me know and I will take the subject

It would be nice if we can go ahead on this before launching other major subject

**Comment by troussej** [comment]
Agreed.

I started some very minor tweaks on :
https://github.com/troussej/BetterDynAdmin/tree/repository-plugin

they don't do anything yet but at least they set the frame :

- wrap the whole BDA script in an anonymous function that loads on document.ready (so that all the different plugins are loaded in order)
- wrap that in try/catch
- load 2 sub scripts, bda.common.js & bda.repository.js (relative load, don't need full url)
-  bda.common.js contains some utility functions, and the basePlugin function
- bda.repository.js just contains a plugin template for now

You can take it from here.

on a side note, I was trying to merge my "edit bookmark" feature, but the master has diverged a bit too much for the merge to be done in sane conditions, so I'll redo that after the global refactor.

**Comment by troussej** [comment]
after putting in place the main elements, it should be possible to split this task between several people.

**Comment by troussej** [comment]
just pushed the refactor of the menu to dev (forgot to add issue nb, sry). Since the child plugin makes reference to BDA, some functions might have not been move, but it does break.

You'll have to reinstall the plugin to take the new files into account

**Comment by jc7447** [comment]
I pushed the new repository module (stable for the most part) and begin the pipeline module (broken for now)

I will try to continue this week.

Complete list of modules I imagine : 
- Commons (to complete)
- Menu (done)
- Toolbar
- Repository (done)
- Pipeline (in progress)
- Perf monitor
- JDBC browser
- Actor
- Component configuration
- XML definition
- Configuration

I would like to split the item tree from the repository part, but there is a lot of dependencies between them.

**Comment by troussej** [comment]
I think it's ok to close.
