### ISSUE TITLE
[Repository] Multi-repo query form / DASH module

### ISSUE THREAD

**Issue by troussej** [jc7447/BetterDynAdmin#72]
Idea: a form that allows to query different repositories at the same time.

Example : check a sku, its stock, its price in one saved request.

**Comment by jc7447** [comment]
I was also thinking about this but as part of a bigger feature "automated scripts", with a very simple syntax we could define a sequence of actions to run like this : 
 
> goto /some/nucleus/component
>  setPropertyValue loggingDebug true
> executeTags : &lt;print-item id="toto" item-descriptor="toto"&gt;
> goto /some/other/component
> executeMethod invalidateCaches

**Comment by troussej** [comment]
Yes.  I wanted to do scripts as well with variables from query to another
Le 22 avr. 2016 20:41, "Jean-Charles Manoury" <notifications@github.com> a
écrit :

**Comment by troussej** [comment]
I guess we'll have to split this big one into more achievable steps ;)

**Comment by troussej** [comment]
that's a subject i'd like to work on.

**Comment by jc7447** [comment]
Which approach do you want to take on this ?

**Comment by troussej** [comment]
I just saw that there is an existing chrome plugin that does something similar:

https://github.com/marlosl/DynamoScript 

the github page has little documentation, but the chrome plugin page shows a bit more

**Comment by troussej** [comment]
Some notes I took about this subject:

 * operations:

```
	query
		- repository
		- params
		- RQL
		- result variable
    callMethod
		- component
		- method
		- result
			- type
			- value
	setProperty
		- component
		- method
	saveVariable
		- source
			- component property
			- rql result
		- variableName

```
* syntax/grammar : how would we parse it? i found http://pegjs.org/ i think the parser should output a JS litteral containing all the different elements, so that it's interpreted in JS, and that could be saved as JSON for further re-use. Command Design Pattern

 * UI/UX : maybe a global overlay so that it's not mistaken with the rest of the dyn admin. Maybe a console-like window, with a result block per instruction. you can delete/redo/save a specific command result

* pre-requisites :
	- refactor the repository and component functions as different jquery-plugin (or other type of modules) so that it can be reused in this feature
		- rql box
		- component set property
		- component call method

**Comment by troussej** [comment]
Small preview of the work in progress

![dash_preview1](https://cloud.githubusercontent.com/assets/8314012/16418596/df96e12e-3d4a-11e6-9696-90ce7dd3ac8d.png)

**Comment by troussej** [comment]
First version pushed to dev.

You'll need to re-install BDA to get the features

- 2 new modules "dash" and "component"
 - component : get/set properties using ajax calls
 - dash : text console to run commands/scripts on BDA + parser in a separate file.
- new libraries
  - scoped bootstrap css (so that it doesn't impact the rest of the css.)
  - bootstrap.js, hacked to be compatible with jquery 3 (changed the validation function :) )
  - typeahead

DASH features
- no button to invoke yet, I'll update menu.js in a next version (I'll add a function to create new menu elements from another plugin
- type "ctrl+alt+t" to invoke the console.
- type help to get the available functions. Mainly get/set component properties for now plus utility. I'll update the wiki to add a manual.

Roadmap : 
- perfs : refactor the dash.build function to only be called on first invocation of the console, not at every page
- repository functions : rql, access saved queries, extract result in variables
- save script functions
- redo script

**Comment by troussej** [comment]
Just pushed a new version to dev. 

I added a section to the localstorage, so please help me test if it works properly on a new install.

- Ability to save scripts with an editor tab.
- init dash only on first openning, not on page load
- redo a script line by clicking "redo" button
- possibility to reference a component using @SHORT where SHORT is a fav short name
- @this refers to current component for quick access
- replaced typeahead with twitter-typeahead & bloodhound for better perfs & UX
- handle synchronisation of multiple commands with a queue & callbacks
- new functions : 
  - print item - added new basic methods in repository : we need to merge them with itemTree functions later

TODO:
- more rql
- save outputs to variables on all functions
- ability to add custom js in the commands to do complex stuff
- documentation / user guide !!!
- save latest tab in use

**Comment by troussej** [comment]
hmm so I guess that now it's pretty fleshed out. 

It's up to you guys to test it out :) Lemme know what you think! (I guess the UX is not exactly the best, for one)

I already used IRL it to set properties on several components at once, and then revert them.

**Comment by jc7447** [comment]
:+1: 

I will try to test it fully this week-end and give you feedback :)

Also, I will probably release 2.0 in the same time

**Comment by troussej** [comment]
hoho 2.0, shiny :)

Btw, I'm still adding stuff, mostly quality of live improvement (ui/ux)

One of my main concern is the syntax, wich is not always intuitive because of conflicts I had with existing patterns, the main being the semicolon vs the dot:

to get the subvalue bar of a var foo , you have to do $foo:bar (semicolon) instead of $foo.bar (more natural), because the dot is used to do /some/component.value and to be compatible with a more complex $someVar:componentpath.$var2.propertyName

I might scratch this entirely and go simply with "method /comp property", and use the dot for subvalues everytime

**Comment by jc7447** [comment]
Further dev will use #103
