### ISSUE TITLE
Repository - Configurable RQL output

### ISSUE THREAD

**Issue by troussej** [jc7447/BetterDynAdmin#81]
Some people prefer the standard xml output instead of tables. 

This could be a configurable settings.

**Comment by jc7447** [comment]
the standard XML is one click away from the table : "Show raw xml" link. 

Don't you think it covers the need ?

**Comment by troussej** [comment]
It's more about having always the xml by default. When discussing about BDA with Martin, he said he didn't like it because he was too used to the normal xml.

So my intention is to have more configuration in BDA, to toggle features so that the tools can be more modulable, and less disruptive with the native D/A.

**Comment by jc7447** [comment]
I agree with you that modularity and feature flipping is a good thing. 

That said, I believe that 99% of BDA user's are happy with the table layout. I would rather develop new feature for 99% of the people than try to satisfy 1%

Anyway, any contribution is welcome and in this case, it would be pretty easy to add a switch and just show the XML.

**Comment by troussej** [comment]
I agree,  just reporting some feedback ;)
Le 18 mai 2016 17:25, "Jean-Charles Manoury" <notifications@github.com> a
écrit :

**Comment by jc7447** [comment]
I won't fix this for now. 

If we received new feedback from users saying that XML is better than table, we can reopen this issue.
