### ISSUE TITLE
Bench similar tools

### ISSUE THREAD

**Issue by troussej** [jc7447/BetterDynAdmin#85]
There are 3 existing chrome ATG plugins, we should take some time to bench them

https://chrome.google.com/webstore/search/atg?hl=en-US

**Comment by jc7447** [comment]
Interesting, I tested them, 

"atg-dynadmin-utils" offers auto-completion in the search input (by making a new Ajax call for each change in the field), seems that there is also tools for the repositories but I don't know how it works, probably broken for my version of Chrome

"Smart ATG Dynamo" offers some shortcuts to create xml tags query and syntax highlight for XML result. Nothing we don't have in BDA

"ATG Dynamo script" seems interesting, pretty much what we discussed in #72. It allows to run script on different dyn/admin but I didn't find any documentation or instructions, I have no idea how the JSON syntax works.

There is also https://github.com/brdloush/atg-dynadmin-repository, which is another userscripts more advanced than the Chrome plugins, there is a lot of shortcuts and ID are clickable in the query result.

**Comment by troussej** [comment]
Another plugin :

https://github.com/vrakoton/atg-chrome-module

This one is developped by Vina Rakotondrainibe, an indep ATG consultant and former ATG/Oracle PS whom I've been working with on LV projects.

It has few features, mainly keyboard shortcuts to act on currrent component

His repo has other ATG related tools as well.

**Comment by onewingedfallen59** [comment]
Benchmark is over ? If so, we can close the issue :)

**Comment by troussej** [comment]
closing ;)
