### ISSUE TITLE
[Component] autocomplete search

### ISSUE THREAD

**Issue by onewingedfallen59** [jc7447/BetterDynAdmin#86]

**Comment by troussej** [comment]
for the typeahead part, #72 includes bloodhout and tw-typeahead.

however i'm affraid of the perfs if doing so much searchs ?

**Comment by onewingedfallen59** [comment]
I've not done anything yet but I think this feature would greatly help developers browsing in a huge quantity of different components so we can begin with a localhost only version and see what happens. For remote envs we may create the feature disable by default or require more characters before triggering an autocomplete search.

**Comment by troussej** [comment]
Yeah if you reuse bloodhoud you can  configure the number of letters. We also should investigate caching the result

**Comment by onewingedfallen59** [comment]
I can't achieve anything with typeahead library, so I'm unassign myself from this issue ^^

**Comment by troussej** [comment]
pushed to dev.

@onewingedfallen59 you can look at the tricks I used to make typeahead and bloodhound work :)

**Comment by jc7447** [comment]
Closing this since it's deployed with version 2.0. We can improve in other issue.

**Comment by onewingedfallen59** [comment]
I know this a closed issue but autocomplete works well. I wonder if we shouldn't make it, at least, enabled by default or remove the switch ?
