### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by onewingedfallen59** [jc7447/BetterDynAdmin#87]
What about non english users ? Most devs would be able to read english but there may be also QA team or PO.

**Comment by troussej** [comment]
well, the dyn/admin itself is in English. Plus the target audience is moslty devs, right? I don't see a PO/QA doing rql request by themselves, unless they are former dev.

Plus IMHO "not speaking english" should not be a valid excuse nowadays ;)

**Comment by jc7447** [comment]
Agree with Joël

Finally, we won't translate component or property names and beside this there is not so much to translate, just some labels.

Dyn/admin is a very technical back-office, the target audience is technical and it is acknowledged that user will understand basic english.

**Comment by onewingedfallen59** [comment]
ok so i close the issue ;)
