### ISSUE TITLE
[Repository] Display xmlDef as table

### ISSUE THREAD

**Issue by troussej** [jc7447/BetterDynAdmin#92]

**Comment by troussej** [comment]
pushed to dev.

**Comment by jc7447** [comment]
The table looks very nice :+1: 

I just have an overlap in OrderRepository for some item descriptor :

![overlap](https://cloud.githubusercontent.com/assets/6620233/18607451/4c4c865e-7ccd-11e6-9aa5-4b413022ff03.jpg)

May be, we can decrease a bit the font size to display more property per page ?

**Comment by sixdouglas** [comment]
It looks really nice indeed.
Maybe we can truncate the name, finish it by '...' and display it fully using the onmouseover. The same way it is done in the query results

**Comment by troussej** [comment]
I think first I'll extend the name column to twice its size. for now the tables are in table-layout-fixed with all columns at 12.5% (1/8) but the last colums with flag values dont need that much.

Then if it still overflows i can add a tooltip like for property descriptors/enums or just an alt title.

**Comment by troussej** [comment]
i reworked this a bit (forgot to mention the ticket in the commit msgs)
* replaced the table by a bootstrap grid for better column sizing & coherence
* added visualisation of derivations.

**Comment by troussej** [comment]
todo:
* links between the xml and the table

**Comment by jc7447** [comment]
The "display as table" button is also displayed for other kind of XML definition, like pipelines or actors.

The button just display an empty list in those cases, we should hide it.

**Comment by troussej** [comment]
todo:
* link from sub-item to super-item

**Comment by troussej** [comment]
fix for "display as table on every page" pushed to dev : I test the "DTD" property to know if it contains "gsa"

**Comment by jc7447** [comment]
The feature works fine now, I'm closing this issue so we can continue to improve in dedicated issue.
