### ISSUE TITLE
Scheduler - Timeline

### ISSUE THREAD

**Issue by troussej** [jc7447/BetterDynAdmin#93]
Visualize in a timeline the next jobs to be run, and the previous jobs
use vis timeline capabilities

**Comment by troussej** [comment]
done;

**Comment by jc7447** [comment]
I tested this with an ATG 11.1 instance with a bunch of scheduler (jms poll, pricing engines, ...), but the timeline is empty :

![timeline](https://cloud.githubusercontent.com/assets/6620233/18366342/a305ba96-7616-11e6-9617-7cacaa08c53c.JPG)

**Comment by troussej** [comment]
hmm I dev'd it on V11.1

Any js logs?

**Comment by jc7447** [comment]
No logs, but after digging a bit I found that the date format seems to be not recognized. 

I have date like this : Sat Sep 10 12:09:30 CEST 2016

`console.log(new Date("Sat Sep 10 12:09:30 CEST 2016"))`

output this :  Date {Invalid Date}

**Comment by troussej** [comment]
Hmm. I don't have a runnable ATG from home, could you send me the html of the page?

(actually I've been collecting html pages to do "offline" work, we could add those as mock pages to the git repo)

**Comment by troussej** [comment]
just commited a fix. looks like "Date(string)" works better than "new Date(string)"
