### ISSUE TITLE
Comment for Dash on Dev

### ISSUE THREAD

**Issue by obedmhg** [jc7447/BetterDynAdmin#98]
Hi Jean,

I wanted to write an script to perform switch catalog on BCC instaance and I tried this:
``
go /atg/commerce/jdbc/ProductCatalogSwitchingDataSource_production
``
and I got this error:
``
$> go /atg/commerce/jdbc/ProductCatalogSwitchingDataSource_production
SyntaxError : Expected ".", "/", [;\n], [a-zA-Z0-9\-], end of input or whitespace but "_" found.
Type help for more information.
``
In BCC instance OOTB there are several components (ProductCatalog_production, ProductCatalog_staging) that have "_" on the name, so I suggest "_" can be part of the RegExp above.

Similar happes when trying to execute rql Query
Defined Query:
``
<query-items item-descriptor="user">
login="$0" AND firstName="$1"
</query-items>
``
``
$> rql @PAR.query [obedmhg@gmail.com, Obed]
SyntaxError : Expected ",", "]", [a-zA-Z0-9\-:/?#._] or whitespace but "@" found.
Type help for more information.
``
@ can be part of one of the arguments..

Not sure if this is bug, since these are found on a dev branch, I just wanted to report them :) so you were awere of them.

Regards,
Obed

**Comment by troussej** [comment]
Hi,

Yes those are bugs. The parser is a bit picky for now so some characters are not accepted because they can be special characters. 

I need to implement escape sequences and allow more chars.

**Comment by troussej** [comment]
Added the possibility to escape special chars (such as @ or . ) by either prefixing them with \ or by wrapping the value with double quotes "

The _ in the first example is now allowed and does not need escaping.

In the future I'll try to make it better, since those chars (@ . ) in those places have no special meaning and could be treated as normal.

**Comment by jc7447** [comment]
I'm closing this since the fix was committed one month ago.

Feel free to reopen if the bug still exists.
